# Generated by Django 4.1 on 2022-09-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'ordering': ['address'], 'verbose_name_plural': 'Email addresses'},
        ),
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Text Messages'},
        ),
    ]
