# Generated by Django 4.1 on 2022-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'ordering': ['address', '-date_added'], 'verbose_name_plural': 'Email addresses'},
        ),
        migrations.AlterField(
            model_name='email',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
