# Generated by Django 4.1 on 2022-09-16 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messanger', '0003_alter_emailaddress_options_alter_textmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='added_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
    ]
