# Generated by Django 4.1 on 2022-10-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0003_alter_emailaddress_options_alter_email_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
