# Generated by Django 4.1 on 2022-09-28 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_alter_attachment_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('replacement_word', models.CharField(blank=True, default=None, max_length=250, verbose_name='suitable replacement word')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
