# Generated by Django 4.1 on 2022-10-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_email_is_draft_textmessage_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date_sent',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='date_sent',
            field=models.DateTimeField(default=None),
        ),
    ]
