# Generated by Django 4.1 on 2022-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0005_blacklistedword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedword',
            name='word',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
