# Generated by Django 4.1 on 2022-10-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0005_alter_email_date_sent_alter_textmessage_date_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-date_created', '-date_sent']},
        ),
        migrations.AlterModelOptions(
            name='textmessage',
            options={'ordering': ['-date_created', '-date_sent'], 'verbose_name_plural': 'Text Messages'},
        ),
        migrations.AlterField(
            model_name='email',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
