# Generated by Django 4.1 on 2022-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0006_alter_blacklistedword_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
