# Generated by Django 4.1 on 2022-09-17 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_telnyxprofile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_idno',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='app_pass',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile owner'),
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='port',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telnyxprofile',
            name='api_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='telnyxprofile',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile owner'),
        ),
    ]
