# Generated by Django 4.1 on 2022-10-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_mail_rate',
            field=models.IntegerField(blank=True, default=5, max_length=10, null=True, verbose_name='Mail Send Rate'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_sms_rate',
            field=models.IntegerField(blank=True, default=5, max_length=10, null=True, verbose_name='SMS Send Rate'),
        ),
    ]
