# Generated by Django 4.1 on 2022-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_preferred_mail_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_mail_rate',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Mail Send Rate'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_sms_rate',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='SMS Send Rate'),
        ),
    ]
