# Generated by Django 4.1 on 2022-09-18 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_idno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprofile',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_profiles', to=settings.AUTH_USER_MODEL, verbose_name='profile owner'),
        ),
        migrations.AlterField(
            model_name='telnyxprofile',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telnyx_profiles', to=settings.AUTH_USER_MODEL, verbose_name='profile owner'),
        ),
    ]
