# Generated by Django 4.1 on 2022-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_wants_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprofile',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='Use SSL'),
        ),
        migrations.AddField(
            model_name='emailprofile',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='port',
            field=models.IntegerField(blank=True, default=465, null=True, verbose_name='Email port'),
        ),
    ]
