# Generated by Django 4.1 on 2022-09-25 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailprofile_use_ssl_emailprofile_use_tls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Profile Number')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_profiles', to=settings.AUTH_USER_MODEL, verbose_name='profile owner')),
            ],
            options={
                'unique_together': {('number', 'owned_by')},
            },
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Profile Email'),
        ),
        migrations.DeleteModel(
            name='TelnyxProfile',
        ),
    ]
