# Generated by Django 4.1 on 2022-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_messageprofile_alter_emailprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprofile',
            name='type',
            field=models.CharField(choices=[('Gmail', 'Gmail'), ('Yahoo', 'Yahoo'), ('Outlook', 'Outlook'), ('Protonmail', 'Protonmail'), ('AOL', 'AOL'), ('Virgin Media', 'Virgin Media'), ('AT&T', 'AT&T'), ('Verizon', 'Verizon')], default='Gmail', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='messageprofile',
            name='account_sid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account SID'),
        ),
        migrations.AddField(
            model_name='messageprofile',
            name='api_client',
            field=models.CharField(choices=[('telnyx', 'Telnyx'), ('twilio', 'Twilio')], max_length=50, null=True, verbose_name='API Client'),
        ),
    ]
