# Generated by Django 4.1 on 2022-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_emailprofile_type_messageprofile_account_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageprofile',
            name='api_client',
        ),
        migrations.AddField(
            model_name='messageprofile',
            name='api_provider',
            field=models.CharField(choices=[('telnyx', 'Telnyx'), ('twilio', 'Twilio')], max_length=50, null=True, verbose_name='API Provider'),
        ),
    ]
