# Generated by Django 4.1 on 2022-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_messageprofile_account_sid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailprofile',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='messageprofile',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_cookies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('Gmail', 'Gmail'), ('Yahoo', 'Yahoo'), ('Outlook', 'Outlook'), ('Protonmail', 'Protonmail'), ('AOL', 'AOL'), ('Virgin Media', 'Virgin Media'), ('AT&T', 'AT&T'), ('Verizon', 'Verizon')], default='Gmail', max_length=50, null=True, verbose_name='Email type'),
        ),
    ]
