# Generated by Django 4.1 on 2022-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_emailprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_privileged',
            field=models.BooleanField(default=False),
        ),
    ]
