# Generated by Django 4.1 on 2022-09-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_creditpackage_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='credit_package',
        ),
        migrations.AddField(
            model_name='purchase',
            name='credit_packages',
            field=models.ManyToManyField(related_name='purchases', to='users.creditpackage', verbose_name='credit packages'),
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='made by'),
        ),
    ]
