# Generated by Django 4.1 on 2022-09-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_purchase_credit_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sid',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Purchase ID'),
        ),
    ]
