# Generated by Django 4.1 on 2022-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_purchase_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount Purchased'),
        ),
    ]
