# Generated by Django 4.1 on 2022-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_purchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_active',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='Price'),
        ),
    ]
