# Generated by Django 4.1 on 2022-10-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_purchase_is_active_purchase_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date_created', '-date_closed']},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='purchase',
            name='charge_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Charge ID'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_closed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
