# Generated by Django 4.1 on 2022-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
