# Generated by Django 4.1 on 2022-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_purchase_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_code',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Coinbase order code'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='charge_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Coinbase charge ID'),
        ),
    ]
