# Generated by Django 4.1 on 2022-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customuser_secret_ans_customuser_secret_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret_ans',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Secret Answer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secret_question',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Secret Question'),
        ),
    ]
